# Generated by Django 5.2.4 on 2025-08-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_logininfo_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.TextField(default='', max_length=500),
        ),
    ]
